global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Service A - CEP Handler
  - job_name: 'service-a'
    static_configs:
      - targets: ['service-a:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Service B - Orchestrator
  - job_name: 'service-b'
    static_configs:
      - targets: ['service-b:8081']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
